spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/supermarket?serverTimezone=UTC

mybatis:
  type-aliases-package: com.myself.mybatisDemo.pojo
  mapper-locations: classpath:mappers/*.xml