import java.util.Date;
import java.text.SimpleDateFormat;
class DaysBetween 
{
	public static void main(String[] args) 
	{
		//从命令行输入日期
		System.out.println("您输入的日期为:");
		System.out.println(args[0]+"-"+args[1]+"-"+args[2]);
		System.out.println();

		//获取当前系统日期
		SimpleDateFormat date=new SimpleDateFormat("yyyy"+"-"+"MM"+"-"+"dd");
		System.out.println("当前系统日期为:");
		System.out.println(date.format(new Date()));
		System.out.println();

		//定义三个字符串分别保存系统时间
		SimpleDateFormat year=new SimpleDateFormat("yyyy");
		SimpleDateFormat month=new SimpleDateFormat("MM");
		SimpleDateFormat day=new SimpleDateFormat("dd");
		String[] str={year.format(new Date()),month.format(new Date()),day.format(new Date())};
		
		//字符型变量转整型变量
		 int a=Integer.parseInt(args[0]);
		 int b=Integer.parseInt(args[1]);
		 int c=Integer.parseInt(args[2]);
		 
		 int x=Integer.parseInt(str[0]);
		 int y=Integer.parseInt(str[1]);
		 int z=Integer.parseInt(str[2]);

		//计算天数差(分别计算两个日期距离0年1月1日相差几天)
		int i,j;	//i记录年数，j记录月数
		int dayDistance1=0;
		int dayDistance2=0;
		int dayDistance3=0;
		//计算dayDistance1
		for (i=0;i<a;i++)
		{
			for(j=1;j<=12;j++)
			{
				//一月
				if(j==1)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
				//二月
				if(j==2)
				{
					//判断当前是否为闰年
					if(i%4==0&&i%100!=0||i%400==0)
					{
						dayDistance1=dayDistance1+29;
						continue;
					}
					else
					{
						dayDistance1=dayDistance1+28;
						continue;
					}
				}
				//三月
				if(j==3)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
				//四月
				if(j==4)
				{
					dayDistance1=dayDistance1+30;
					continue;
				}
				//五月
				if(j==5)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
				//六月
				if(j==6)
				{
					dayDistance1=dayDistance1+30;
					continue;
				}
				//七月
				if(j==7)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
				//八月
				if(j==8)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
				//九月
				if(j==9)
				{
					dayDistance1=dayDistance1+30;
					continue;
				}
				//十月
				if(j==10)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
				//十一月
				if(j==11)
				{
					dayDistance1=dayDistance1+30;
					continue;
				}
				//十二月
				if(j==12)
				{
					dayDistance1=dayDistance1+31;
					continue;
				}
			}
		}
		for(j=1;j<b;j++)
		{
			//一月
			if(j==1)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
			//二月
			if(j==2)
			{
				//判断当前是否为闰年
				if(i%4==0&&i%100!=0||i%400==0)
				{
					dayDistance1=dayDistance1+29;
					continue;
				}
				else
				{
					dayDistance1=dayDistance1+28;
					continue;
				}
			}
			//三月
			if(j==3)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
			//四月
			if(j==4)
			{
				dayDistance1=dayDistance1+30;
				continue;
			}
			//五月
			if(j==5)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
			//六月
			if(j==6)
			{
				dayDistance1=dayDistance1+30;
				continue;
			}
			//七月
			if(j==7)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
			//八月
			if(j==8)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
			//九月
			if(j==9)
			{
				dayDistance1=dayDistance1+30;
				continue;
			}
			//十月
			if(j==10)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
			//十一月
			if(j==11)
			{
				dayDistance1=dayDistance1+30;
				continue;
			}
			//十二月
			if(j==12)
			{
				dayDistance1=dayDistance1+31;
				continue;
			}
		}
		if(c!=1)
			dayDistance1=dayDistance1+c;
		//计算dayDistance2
				for (i=0;i<x;i++)
				{
					for(j=1;j<=12;j++)
					{
						//一月
						if(j==1)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
						//二月
						if(j==2)
						{
							//判断当前是否为闰年
							if(i%4==0&&i%100!=0||i%400==0)
							{
								dayDistance2=dayDistance2+29;
								continue;
							}
							else
							{
								dayDistance2=dayDistance2+28;
								continue;
							}
						}
						//三月
						if(j==3)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
						//四月
						if(j==4)
						{
							dayDistance2=dayDistance2+30;
							continue;
						}
						//五月
						if(j==5)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
						//六月
						if(j==6)
						{
							dayDistance2=dayDistance2+30;
							continue;
						}
						//七月
						if(j==7)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
						//八月
						if(j==8)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
						//九月
						if(j==9)
						{
							dayDistance2=dayDistance2+30;
							continue;
						}
						//十月
						if(j==10)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
						//十一月
						if(j==11)
						{
							dayDistance2=dayDistance2+30;
							continue;
						}
						//十二月
						if(j==12)
						{
							dayDistance2=dayDistance2+31;
							continue;
						}
					}
				}
				for(j=1;j<y;j++)
				{
					//一月
					if(j==1)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
					//二月
					if(j==2)
					{
						//判断当前是否为闰年
						if(i%4==0&&i%100!=0||i%400==0)
						{
							dayDistance2=dayDistance2+29;
							continue;
						}
						else
						{
							dayDistance2=dayDistance2+28;
							continue;
						}
					}
					//三月
					if(j==3)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
					//四月
					if(j==4)
					{
						dayDistance2=dayDistance2+30;
						continue;
					}
					//五月
					if(j==5)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
					//六月
					if(j==6)
					{
						dayDistance2=dayDistance2+30;
						continue;
					}
					//七月
					if(j==7)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
					//八月
					if(j==8)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
					//九月
					if(j==9)
					{
						dayDistance2=dayDistance2+30;
						continue;
					}
					//十月
					if(j==10)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
					//十一月
					if(j==11)
					{
						dayDistance2=dayDistance2+30;
						continue;
					}
					//十二月
					if(j==12)
					{
						dayDistance2=dayDistance2+31;
						continue;
					}
				}
				if(z!=1)
					dayDistance2=dayDistance2+z;
				//输出两个日期天数差
				dayDistance3=dayDistance2-dayDistance1;
				System.out.println("两个日期之间共相差"+dayDistance3+"天");
	}
}